spring:
  import: configserver:http://configserver:8071/  
  datasource:
    url: jdbc:mysql://192.168.118.108:3306/accountsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always  
  rabbitmq:
    host: "192.168.118.108"
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: always

eureka:
  security:
    user:
      name: user
      password: password
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://${eureka.security.user.name}:${eureka.security.user.password}@eurekaserver:8070/eureka/
    # Client local cache update frequency
    registry-fetch-interval-seconds: 30
  instance:
    preferIpAddress: true
    # Interval between two heartbeats sent to the server
    lease-renewal-interval-in-seconds: 30
    # Expiration time before eviction if no more heartbeat
    lease-expiration-duration-in-seconds: 90

build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related docker APIs"
  contactDetails:
    name: "Yassin Mellouki - Developer"
    email: "y.mellouki@eazybank.com"
  onCallSupport:
    - '{cipher}4fec0be050f605ec2d87d3f66e18d795cf40cb381e80087ad4e5c6bb5ebcd657'
    - '{cipher}5d36bf8e22723f358502459a9184aaa918e7a9e68faed5ac2bc8c72339ccfba2'