spring:
  datasource:
    url: jdbc:mysql://192.168.118.108:3308/cardsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always  
  rabbitmq:
    host: "192.168.118.108"
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      show-values: never

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://192.168.118.108:8070/eureka/
  
build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related docker APIs"
  contactDetails:
    name: "Yassin Mellouki - Developer"
    email: "y.mellouki@eazybank.com"
  onCallSupport:
    - '{cipher}4fec0be050f605ec2d87d3f66e18d795cf40cb381e80087ad4e5c6bb5ebcd657'
    - '{cipher}5d36bf8e22723f358502459a9184aaa918e7a9e68faed5ac2bc8c72339ccfba2'