build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs"
  contactDetails:
    name: "Choma Lech - Developer"
    email: "c.hchjt@eazybank.com"
  onCallSupport:
    - '{cipher}1c5c50a3410ea05f797ff2e9a13617b86b3eedae4d0ce30ddc5d4c6bb7e8d2fe'
    - '{cipher}2f7788fe792b356ee1de1fe15c67b49e234abf6f1a5868ad460da73293329aa4'

spring:
  rabbitmq:
    username: guest
    password: guest

management:
  endpoint:
    env:
      show-values: always