build:
  version: "1.0"

loans:
  message: "Hey, welcome to EazyBank loans related prod APIs"
  contactDetails:
    name: "Pelias Sudhir - Product Owner"
    email: "pelias@eazybank.com"
  onCallSupport:
    - (723) 656-8709
    - (156) 342-0956

spring:
  rabbitmq:
    username: guest
    password: guest

management:
  endpoint:
    env:
      show-values: always